---
- apt: name=apt-mirror
  ignore_errors: yes
- name: drop config
  template: src=mirror.list dest=/etc/apt/mirror.list
- name: fix mirror ownership
  file: path="{{ apt_mirror_base }}" owner=apt-mirror group=apt-mirror recurse=yes
- name: Add cron job
  cron: name="apt-mirror" minute="4" hour="4" user="apt-mirror" job="/usr/bin/apt-mirror > /var/spool/apt-mirror/var/cron.log" cron_file="apt-mirror"